= El problema de los fumadores de cigarrillos (Patil 1971)

Considere un sistema con tres procesos fumadores y un proceso agente. Cada fumador 
está continuamente armando y fumando cigarrillos. Sin embargo, para armar un cigarrillo, 
el fumador necesita tres ingredientes: tabaco, papel y fósforos. Uno de los procesos 
fumadores tiene papel, otro tiene el tabaco y el tercero los fósforos. El agente 
tiene una cantidad infinita de los tres materiales. El agente coloca dos de los 
ingredientes sobre la mesa. El fumador que tiene el ingrediente restante armaría 
un cigarrillo y se lo fuma, avisando al agente cuando termina. Entonces, el agente
coloca dos de los tres ingredientes y se repite el ciclo. 

== Implementación

Para la solución de este problema se requieren 3 semáforos (uno para cada fumador), 
y otro para el agente.

----
def agente()

    while true {
        wait(mesa)
        ingredients = obtain_ingredients()
        case ingredients
            PAPER_TOBACCO:
                signal(matches)
            PAPER_MATCHES:
                signal(tobacco)
            TOBACCO_MATCHES:
                signal(paper)
    }
----

----
def fumador(i)

    while true {
        wait(sem[i])
        smoke()
        signal(mesa)
    }
----